// =============================================
//  TV Supreme Admin — Mock Data
// =============================================

export const STATS = {
  totalNews: 2467,
  programs: 15,
  ytVideos: 873,
  members: 1247,
  dailyViews: 48230,
  liveViewers: 1203,
  pages: 41,
  comments: 1,
};

export const NEWS_ITEMS = [
  { id: 1, title: 'ආනෙමු ස්ථානමේලට මිලදී ගැනීමේ පිරිස් නඩු', category: 'Breaking News', status: 'Published', date: '2026-06-12', author: 'Kasun Silva' },
  { id: 2, title: 'T20 World Cup 2026 — Sri Lanka Squad Announced', category: 'Sports News', status: 'Published', date: '2026-06-11', author: 'Ruwan Perera' },
  { id: 3, title: 'Economy grows 3.2% in Q1 2026 — Central Bank Report', category: 'Business News', status: 'Published', date: '2026-06-11', author: 'Nimal Fernando' },
  { id: 4, title: 'Sports ශ්‍රී Supreme Episode 47 — Full Highlights', category: 'Sports News', status: 'Published', date: '2026-06-10', author: 'Kasun Silva' },
  { id: 5, title: 'ජනාධිපතිවරයා ඉන්දියාවට ගිය ගමන — විශේෂ වාර්තාව', category: 'Foreign News', status: 'Published', date: '2026-06-10', author: 'Dilani Jayawardena' },
  { id: 6, title: 'Pakistan T20I Tri-Series — Day 3 Match Report', category: 'Sports News', status: 'Published', date: '2026-06-09', author: 'Ruwan Perera' },
  { id: 7, title: 'ශ්‍රී ලංකා රජය නව ආර්ථික ප්‍රතිසංස්කරණ ප්‍රකාශ කරයි', category: 'Latest Reports', status: 'Published', date: '2026-06-09', author: 'Nimal Fernando' },
  { id: 8, title: 'Colombo Port City — New Investment Milestone Reached', category: 'Business News', status: 'Published', date: '2026-06-08', author: 'Dilani Jayawardena' },
  { id: 9, title: 'CNA on TV Supreme — Special Edition: South Asia Update', category: 'Foreign News', status: 'Published', date: '2026-06-08', author: 'Kasun Silva' },
  { id: 10, title: 'ගොවිජන ගැලවිය — ගොවි ජනතාවගේ ඉල්ලීම් ලැයිස්තුව', category: 'Latest Reports', status: 'Draft', date: '2026-06-07', author: 'Sunil Banda' },
  { id: 11, title: 'Supreme TV Digital Academy — Batch 4 Applications Open', category: 'Breaking News', status: 'Draft', date: '2026-06-07', author: 'Dilani Jayawardena' },
  { id: 12, title: 'Hathara Wate — Housing Prices Up 14% in Colombo District', category: 'News Bulletin', status: 'Published', date: '2026-06-06', author: 'Nimal Fernando' },
];

export const PROGRAMS = [
  { id: 1, title: 'Samanmaliya', category: 'Dramas', status: 'Active', thumbnail: '🎭', airTime: '22:00 Daily' },
  { id: 2, title: 'Yowun Wasanthe', category: 'Dramas', status: 'Active', thumbnail: '🌸', airTime: '14:00 Weekdays' },
  { id: 3, title: 'Global Pulse', category: 'Infotainment', status: 'Active', thumbnail: '🌐', airTime: '13:00 Weekdays' },
  { id: 4, title: 'ජననිදි (Jana Handa)', category: 'Infotainment', status: 'Active', thumbnail: '🎤', airTime: '20:00 Weekends' },
  { id: 5, title: 'ව්‍යාරාමය', category: 'Religious', status: 'Active', thumbnail: '🙏', airTime: '05:30 Daily' },
  { id: 6, title: 'Saddharmalankaraya', category: 'Religious', status: 'Active', thumbnail: '☸️', airTime: '06:00 Daily' },
  { id: 7, title: 'Every Morning', category: 'Lifestyle', status: 'Active', thumbnail: '☀️', airTime: '08:00 Weekdays' },
  { id: 8, title: 'Ithin Ithin Kohomada', category: 'Entertainment', status: 'Active', thumbnail: '😂', airTime: '09:30 Weekdays' },
  { id: 9, title: 'CNA on TV Supreme', category: 'News', status: 'Active', thumbnail: '📡', airTime: '04:50 & 07:00' },
  { id: 10, title: 'PJFM', category: 'Religious', status: 'Active', thumbnail: '🕌', airTime: '07:30 Daily' },
  { id: 11, title: 'Hathara Wate', category: 'News', status: 'Active', thumbnail: '🏘️', airTime: '06:30 Weekdays' },
  { id: 12, title: 'Sports Supreme', category: 'Sports', status: 'Active', thumbnail: '⚽', airTime: '21:00 Daily' },
  { id: 13, title: 'Biz Digest', category: 'Business', status: 'Active', thumbnail: '💼', airTime: '17:30 Weekdays' },
  { id: 14, title: 'Road to Weekend', category: 'Entertainment', status: 'Active', thumbnail: '🎉', airTime: '19:00 Fri' },
  { id: 15, title: 'Kavi Naduwa', category: 'Entertainment', status: 'Active', thumbnail: '🎵', airTime: '20:30 Sat' },
];

export const SCHEDULE = {
  Monday: [
    { time: '04:50', program: 'CNA on TV Supreme', category: 'News' },
    { time: '05:00', program: 'Asiri Diri Piritha', category: 'Religious' },
    { time: '05:30', program: 'ව්‍යාරාමය', category: 'Religious' },
    { time: '06:00', program: 'Saddharmalankaraya', category: 'Religious' },
    { time: '06:30', program: 'Hathara Wate', category: 'News' },
    { time: '07:00', program: 'CNA on TV Supreme', category: 'News' },
    { time: '07:30', program: 'PJFM', category: 'Religious' },
    { time: '08:00', program: 'Every Morning — Taru Udesana', category: 'Lifestyle' },
    { time: '08:30', program: 'Every Morning — Heda Weda Udesana', category: 'Lifestyle' },
    { time: '09:30', program: 'Ithin Ithin Kohomada', category: 'Entertainment' },
    { time: '12:00', program: 'News Bulletin', category: 'News' },
    { time: '13:00', program: 'Global Pulse', category: 'Infotainment' },
    { time: '14:00', program: 'Yowun Wasanthe', category: 'Dramas' },
    { time: '17:30', program: 'Biz Digest', category: 'Business' },
    { time: '19:30', program: 'News Bulletin', category: 'News' },
    { time: '20:00', program: 'Janahada', category: 'Infotainment' },
    { time: '21:00', program: 'Sports Supreme', category: 'Sports' },
    { time: '22:00', program: 'Samanmaliya', category: 'Dramas' },
  ],
  Tuesday: [
    { time: '04:50', program: 'CNA on TV Supreme', category: 'News' },
    { time: '05:00', program: 'Asiri Diri Piritha', category: 'Religious' },
    { time: '05:30', program: 'ව්‍යාරාමය', category: 'Religious' },
    { time: '06:00', program: 'Saddharmalankaraya', category: 'Religious' },
    { time: '06:30', program: 'Hathara Wate', category: 'News' },
    { time: '07:00', program: 'CNA on TV Supreme', category: 'News' },
    { time: '07:30', program: 'PJFM', category: 'Religious' },
    { time: '08:00', program: 'Every Morning — Taru Udesana', category: 'Lifestyle' },
    { time: '09:30', program: 'Ithin Ithin Kohomada', category: 'Entertainment' },
    { time: '12:00', program: 'News Bulletin', category: 'News' },
    { time: '13:00', program: 'Global Pulse', category: 'Infotainment' },
    { time: '14:00', program: 'Yowun Wasanthe', category: 'Dramas' },
    { time: '19:30', program: 'News Bulletin', category: 'News' },
    { time: '20:00', program: 'ජනනිදි Special', category: 'Infotainment' },
    { time: '21:00', program: 'Sports Supreme', category: 'Sports' },
    { time: '22:00', program: 'Samanmaliya', category: 'Dramas' },
  ],
  Wednesday: [
    { time: '04:50', program: 'CNA on TV Supreme', category: 'News' },
    { time: '05:30', program: 'ව්‍යාරාමය', category: 'Religious' },
    { time: '06:00', program: 'Saddharmalankaraya', category: 'Religious' },
    { time: '06:30', program: 'Hathara Wate', category: 'News' },
    { time: '07:00', program: 'CNA on TV Supreme', category: 'News' },
    { time: '07:30', program: 'PJFM', category: 'Religious' },
    { time: '08:00', program: 'Every Morning', category: 'Lifestyle' },
    { time: '09:30', program: 'Ithin Ithin Kohomada', category: 'Entertainment' },
    { time: '12:00', program: 'News Bulletin', category: 'News' },
    { time: '13:00', program: 'Global Pulse', category: 'Infotainment' },
    { time: '14:00', program: 'Yowun Wasanthe', category: 'Dramas' },
    { time: '17:30', program: 'Biz Digest', category: 'Business' },
    { time: '19:30', program: 'News Bulletin', category: 'News' },
    { time: '20:30', program: 'Kavi Naduwa', category: 'Entertainment' },
    { time: '21:00', program: 'Sports Supreme', category: 'Sports' },
    { time: '22:00', program: 'Samanmaliya', category: 'Dramas' },
  ],
  Thursday: [
    { time: '04:50', program: 'CNA on TV Supreme', category: 'News' },
    { time: '05:30', program: 'ව්‍යාරාමය', category: 'Religious' },
    { time: '06:00', program: 'Saddharmalankaraya', category: 'Religious' },
    { time: '06:30', program: 'Hathara Wate', category: 'News' },
    { time: '07:00', program: 'CNA on TV Supreme', category: 'News' },
    { time: '08:00', program: 'Every Morning', category: 'Lifestyle' },
    { time: '09:30', program: 'Ithin Ithin Kohomada', category: 'Entertainment' },
    { time: '12:00', program: 'News Bulletin', category: 'News' },
    { time: '13:00', program: 'Global Pulse', category: 'Infotainment' },
    { time: '14:00', program: 'Yowun Wasanthe', category: 'Dramas' },
    { time: '19:30', program: 'News Bulletin', category: 'News' },
    { time: '20:00', program: 'Janahada', category: 'Infotainment' },
    { time: '21:00', program: 'Sports Supreme', category: 'Sports' },
    { time: '22:00', program: 'Samanmaliya', category: 'Dramas' },
  ],
  Friday: [
    { time: '04:50', program: 'CNA on TV Supreme', category: 'News' },
    { time: '05:30', program: 'ව්‍යාරාමය', category: 'Religious' },
    { time: '06:00', program: 'Saddharmalankaraya', category: 'Religious' },
    { time: '06:30', program: 'Hathara Wate', category: 'News' },
    { time: '07:00', program: 'CNA on TV Supreme', category: 'News' },
    { time: '07:30', program: 'PJFM', category: 'Religious' },
    { time: '08:00', program: 'Every Morning', category: 'Lifestyle' },
    { time: '09:30', program: 'Ithin Ithin Kohomada', category: 'Entertainment' },
    { time: '12:00', program: 'News Bulletin', category: 'News' },
    { time: '13:00', program: 'Global Pulse', category: 'Infotainment' },
    { time: '14:00', program: 'Yowun Wasanthe', category: 'Dramas' },
    { time: '17:30', program: 'Biz Digest', category: 'Business' },
    { time: '19:00', program: 'Road to Weekend', category: 'Entertainment' },
    { time: '19:30', program: 'News Bulletin', category: 'News' },
    { time: '21:00', program: 'Sports Supreme', category: 'Sports' },
    { time: '22:00', program: 'Samanmaliya', category: 'Dramas' },
  ],
  Saturday: [
    { time: '05:00', program: 'Asiri Diri Piritha', category: 'Religious' },
    { time: '05:30', program: 'ව්‍යාරාමය', category: 'Religious' },
    { time: '06:30', program: 'Saddharmalankaraya', category: 'Religious' },
    { time: '08:00', program: 'Every Morning Weekend', category: 'Lifestyle' },
    { time: '10:00', program: 'Kids Supreme', category: 'Entertainment' },
    { time: '12:00', program: 'News Bulletin', category: 'News' },
    { time: '13:00', program: 'CNA Weekend Edition', category: 'News' },
    { time: '15:00', program: 'Global Pulse', category: 'Infotainment' },
    { time: '17:00', program: 'Sports Highlights', category: 'Sports' },
    { time: '19:30', program: 'News Bulletin', category: 'News' },
    { time: '20:00', program: 'ජනනිදි (Jana Handa)', category: 'Infotainment' },
    { time: '20:30', program: 'Kavi Naduwa', category: 'Entertainment' },
    { time: '21:30', program: 'Sports Supreme Weekend', category: 'Sports' },
    { time: '22:30', program: 'Samanmaliya', category: 'Dramas' },
  ],
  Sunday: [
    { time: '05:00', program: 'Asiri Diri Piritha', category: 'Religious' },
    { time: '06:00', program: 'Saddharmalankaraya', category: 'Religious' },
    { time: '07:00', program: 'PJFM Sunday', category: 'Religious' },
    { time: '09:00', program: 'Every Morning Sunday', category: 'Lifestyle' },
    { time: '11:00', program: 'Kids Supreme', category: 'Entertainment' },
    { time: '12:00', program: 'News Bulletin', category: 'News' },
    { time: '14:00', program: 'Yowun Wasanthe', category: 'Dramas' },
    { time: '16:00', program: 'CNA Weekend', category: 'News' },
    { time: '17:30', program: 'Global Pulse', category: 'Infotainment' },
    { time: '19:30', program: 'News Bulletin', category: 'News' },
    { time: '20:00', program: 'Janahada Sunday Special', category: 'Infotainment' },
    { time: '21:00', program: 'Sports Supreme', category: 'Sports' },
    { time: '22:00', program: 'Samanmaliya', category: 'Dramas' },
  ],
};

export const YT_VIDEOS = [
  { id: 1, title: 'ජනනිදි | Jana Handa | 2026.06.01 | Full Episode', videoId: 'jnh060126', channel: 'TV Supreme', publishDate: '2026-06-01', status: 'Published' },
  { id: 2, title: 'ව්‍යාරාමය | 2026.06.05 | Morning Prayers Live', videoId: 'vya060526', channel: 'TV Supreme', publishDate: '2026-06-05', status: 'Published' },
  { id: 3, title: 'Sports ශ්‍රී Supreme | Episode 47 | 2026.05.23', videoId: 'spt052326', channel: 'TV Supreme', publishDate: '2026-05-23', status: 'Published' },
  { id: 4, title: 'Samanmaliya | Episode 182 | 2026.06.10 | සමන්මාලිය', videoId: 'sam061026', channel: 'TV Supreme', publishDate: '2026-06-10', status: 'Published' },
  { id: 5, title: 'Hathara Wate News | 2026.06.12 | හතර වතේ', videoId: 'hw061226', channel: 'TV Supreme', publishDate: '2026-06-12', status: 'Published' },
  { id: 6, title: 'Global Pulse | CNA on TV Supreme | 2026.06.11', videoId: 'gp061126', channel: 'TV Supreme', publishDate: '2026-06-11', status: 'Published' },
  { id: 7, title: 'Yowun Wasanthe | Episode 95 | 2026.06.09 | යොවුන් වාසන්තේ', videoId: 'yw060926', channel: 'TV Supreme', publishDate: '2026-06-09', status: 'Published' },
  { id: 8, title: 'Kavi Naduwa | 2026.06.07 | Music Spectacular', videoId: 'kn060726', channel: 'TV Supreme', publishDate: '2026-06-07', status: 'Published' },
  { id: 9, title: 'PJFM | Friday Sermon | 2026.06.06', videoId: 'pjfm060626', channel: 'TV Supreme', publishDate: '2026-06-06', status: 'Published' },
  { id: 10, title: 'Ithin Ithin Kohomada | Best Moments 2026 Compilation', videoId: 'iik060426', channel: 'TV Supreme', publishDate: '2026-06-04', status: 'Published' },
  { id: 11, title: 'Biz Digest | Economy Special | ව්‍යාපාර විශේෂ | 2026.06.03', videoId: 'bd060326', channel: 'TV Supreme', publishDate: '2026-06-03', status: 'Draft' },
  { id: 12, title: 'Road to Weekend | Full Show | 2026.06.01 | සෙනසුරාදා', videoId: 'rtw060126', channel: 'TV Supreme', publishDate: '2026-06-01', status: 'Draft' },
];

export const COMMENTS = [
  { id: 1, author: 'Pasindu', email: 'pasindusanjula200404211619@gmail.com', ip: '192.248.32.221', comment: 'good', post: 'Pakistan T20I Tri-Series', date: '2026-02-15', status: 'Approved' },
  { id: 2, author: 'Sanduni Perera', email: 'sanduni.p@gmail.com', ip: '112.134.56.88', comment: 'ඉතා හොඳ වාර්තාවක්! ස්තූතියි TV Supreme!', post: 'ජනාධිපතිවරයා ඉන්දියාවට ගිය ගමන', date: '2026-06-10', status: 'Approved' },
  { id: 3, author: 'Dimuth K', email: 'dimuth.k@hotmail.com', ip: '203.94.18.44', comment: 'Please add more sports content. Love the channel!', post: 'Sports Supreme Episode 47', date: '2026-06-09', status: 'Pending' },
  { id: 4, author: 'Unknown User', email: 'spam@promo.xyz', ip: '45.67.89.101', comment: 'Buy cheap followers! Click here...', post: 'Any Post', date: '2026-06-08', status: 'Spam' },
  { id: 5, author: 'Chamari W', email: 'chamari.w@yahoo.com', ip: '172.16.40.22', comment: 'Samanmaliya episode 180 was incredible! Best drama this year.', post: 'Samanmaliya Episode 180', date: '2026-06-07', status: 'Approved' },
];

export const CONTACTS = [
  { id: 1, name: 'Ruwan Jayasekara', type: 'News Tip', email: 'ruwan.j@gmail.com', message: 'I have information regarding the Colombo port corruption case. Please contact me urgently.', date: '2026-06-12', status: 'Open' },
  { id: 2, name: 'Lanka Advertisers Pvt Ltd', type: 'Advertise', email: 'media@lankaads.lk', message: 'We would like to discuss a 3-month prime-time advertising package for our new product launch.', date: '2026-06-12', status: 'Open' },
  { id: 3, name: 'Amara Silva', type: 'General', email: 'amara.s@yahoo.com', message: 'Great work on the Samanmaliya drama. Please keep it going! When does the next season start?', date: '2026-06-11', status: 'Resolved' },
  { id: 4, name: 'Dinesh Fernando', type: 'Complaint', email: 'dinesh.f@outlook.com', message: 'The live stream was buffering heavily during last night\'s news bulletin. Please fix the streaming quality.', date: '2026-06-11', status: 'Open' },
  { id: 5, name: 'TechCorp Solutions', type: 'Advertise', email: 'ads@techcorp.lk', message: 'Interested in sponsoring the Biz Digest program. What are the rates for a 1-year sponsorship?', date: '2026-06-10', status: 'Resolved' },
  { id: 6, name: 'Nadeeka Rathnayake', type: 'Technical', email: 'nadeeka.r@gmail.com', message: 'The website is not loading properly on mobile Chrome. Getting a white screen after login.', date: '2026-06-10', status: 'Open' },
  { id: 7, name: 'Prasad Wickramasinghe', type: 'News Tip', email: 'prasad.w@gmail.com', message: 'Saw illegal dumping near Biyagama industrial zone. Have video evidence I can share.', date: '2026-06-09', status: 'Open' },
  { id: 8, name: 'Yasara Wijesekara', type: 'General', email: 'yasara.w@hotmail.com', message: 'Please add subtitles to the CNA on TV Supreme broadcasts. It would help hearing-impaired viewers.', date: '2026-06-09', status: 'Resolved' },
  { id: 9, name: 'Gayan Enterprises', type: 'Advertise', email: 'info@gayanent.lk', message: 'We want to advertise our new retail chain on TV Supreme. Please send media kit and rates.', date: '2026-06-08', status: 'Resolved' },
  { id: 10, name: 'Malith Senanayake', type: 'Complaint', email: 'malith.s@gmail.com', message: 'Breaking news alert was 2 hours late compared to other channels. Need to improve news speed.', date: '2026-06-07', status: 'Resolved' },
];

export const CAREERS = [
  { id: 1, title: 'Senior News Reporter', department: 'News & Current Affairs', type: 'Full-time', deadline: '2026-06-30', applications: 14, status: 'Active' },
  { id: 2, title: 'Video Editor — Dramas', department: 'Production', type: 'Full-time', deadline: '2026-07-10', applications: 9, status: 'Active' },
  { id: 3, title: 'Digital Marketing Executive', department: 'Marketing', type: 'Full-time', deadline: '2026-06-25', applications: 21, status: 'Active' },
  { id: 4, title: 'Camera Operator (OB Van)', department: 'Production', type: 'Contract', deadline: '2026-06-20', applications: 6, status: 'Active' },
  { id: 5, title: 'Web Developer (React)', department: 'Digital', type: 'Full-time', deadline: '2026-07-15', applications: 18, status: 'Active' },
  { id: 6, title: 'Social Media Manager', department: 'Digital', type: 'Full-time', deadline: '2026-07-05', applications: 11, status: 'Active' },
];

export const PLATFORM_STATS = {
  youtube: { subscribers: '359K', videos: 873, views: '2.1M', growth: '+12%', monthlyViews: '480K' },
  facebook: { followers: '241K', reach: '890K', growth: '+8%', engagement: '4.2%' },
  tiktok: { followers: '89K', views: '1.2M', growth: '+34%', avgViews: '48K' },
  whatsapp: { subscribers: '45K', growth: '+21%', messages: '12K/day' },
};
